//16 oktabr//
// array itertion
// const numbers = [1, 2, 3, 4, 5];
// for (let i < numbers.length i++)  
//    if (numbers[i] % 2 === 0) {
// console.log(numbers[i])
// }
// }

// const numbers=[1,2,3,4,5];
// let sum=0
// for(let i=0; i<numbers.length;i++){
// sum+=numbers[i];
// }
// console.log(sum);
// const numbers = [1, 2, 3, 4, 5]

// for (let i = 0; i < numbers.length; i++) {
// console.log(numbers[i] * 2)
// }
// const numbers = [1, 2, 3, 4, 5];
// for (let i = 0; i < arr.length; i++) {
// if (arr[i] > 0) 
//  
//   }


// const numbers = [1, 2, 3, 4, 5];
// numbers.forEach(function(element,index,array){
// console.log(index);
// });
// numbers.forEach(number)=>{
// console.log(number*2);
// }
//map
// const product = [
// { name: 'kofe', price: 25000 },
// { name: 'choy', price: 18000 },
// { name: 'sut', price: 12000 },
// ];
// const TAXproducts = product.map((product) => {
// return {
// product,
// taxprice: Math.trunc(product.price * 1.12),
// };
// });
// console.log(TAXproducts);

// 18-oktabr//dars davomi
// /
// const arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
// for (let i = 0; i < arr.length; i++) {
// console.log(arr[i]);
// }
// qoshimcha
// const arri = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
// for (let i = 10; i < = 20;) {
// console.log(i);
// }

// Array.forEach((value, index, array) => {
// console.log(value);
// });
//foreach//
// let fruits = ['apple', ' banana', 'cherry'];
// fruits.forEach((fruit, i, array) => {
// console.log(i + '.' + fruits)
// });
//map
// const arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
// const newarr = arr.map((value, index, array) => {
// return value ** 2;
// });
// console.log(newarr);
// filter//
// if (value % 2 === 0) {
// ;
// };
// console.log(newarr)
// 1-mashq
// const users = [
// { name: "Ali", status: "active" },
// { name: "Vali", status: "banned" },
// { name: "Aziza", status: 'active' },
// ];
// const activeUsers = users.filter(user => user.status === "active");
// console.log(activeUsers);
// 2-mashq
// const cart = [
//  { name: "Laptop", price: 7000000, qty: 1 },
//  { name: "Sichqoncha", price: 120000, qty: 2 },
//  { name: "Klaviatura", price: 250000,qty:1},
// ];
// 
// const prisesum = cart.reduce((prevval,curval,index,array) => {
// console.log(prevval);
// console.log(index);
// }, 0);

// const transactions = [
    // { type: "deposit", amount: 2000 },
    // { type: "withdraw", amount: 500 },
    // { type: "deposit", amount: 300 },
// ];
// const balance = transactions.reduce((balance, curVal) => {
    // if (curval.type === 'deposit') {
        // balance += curVal.amout
    // } else {
        // balance -= curval.amount
    // }
    // return balance
// }, 0)
// console.log(balance)

//21-octomber

//js class


















